baseURL = "https://juliusyu327.github.io/"
defaultContentLanguage = "zh-tw"
enableRobotsTXT = true
enableEmoji = true
summaryLength = 30

[pagination]
  pagerSize = 20

[outputs]
  home = ["HTML", "RSS", "JSON"]

[imaging]
  anchor = "Center"

[sitemap]
  changefreq = "weekly"
  filename = "sitemap.xml"
  priority = 0.5
