[[main]]
  name = "專案"
  pageRef = "projects"
  weight = 10

[[main]]
  name = "技術"
  pageRef = "skills"
  weight = 20

[[main]]
  name = "筆記"
  pageRef = "notes"
  weight = 30

[[main]]
  name = "About"
  pageRef = "about"
  weight = 40
